#!/bin/sh

if [ ! "$1" = "" ]; then
    OLD_LFV=$LFV_DEFAULT_FOLDER
    LFV_DEFAULT_FOLDER="$(cd "$1" && pwd -P)"
fi

echo $LFV_DEFAULT_FOLDER

cd ~/code/local-files-viewer/
npm run dev

LFV_DEFAULT_FOLDER=$OLD_LFV
